/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface RegisterRoleInterface extends ethers.utils.Interface {
  functions: {
    "hasOperator(address)": FunctionFragment;
    "metaspacecyAccessControls()": FunctionFragment;
    "registerOperator()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "hasOperator", values: [string]): string;
  encodeFunctionData(
    functionFragment: "metaspacecyAccessControls",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerOperator",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "hasOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaspacecyAccessControls",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerOperator",
    data: BytesLike
  ): Result;

  events: {};
}

export class RegisterRole extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: RegisterRoleInterface;

  functions: {
    hasOperator(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[boolean] & { isOperator: boolean }>;

    "hasOperator(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[boolean] & { isOperator: boolean }>;

    metaspacecyAccessControls(overrides?: CallOverrides): Promise<[string]>;

    "metaspacecyAccessControls()"(overrides?: CallOverrides): Promise<[string]>;

    registerOperator(overrides?: Overrides): Promise<ContractTransaction>;

    "registerOperator()"(overrides?: Overrides): Promise<ContractTransaction>;
  };

  hasOperator(addr: string, overrides?: CallOverrides): Promise<boolean>;

  "hasOperator(address)"(
    addr: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  metaspacecyAccessControls(overrides?: CallOverrides): Promise<string>;

  "metaspacecyAccessControls()"(overrides?: CallOverrides): Promise<string>;

  registerOperator(overrides?: Overrides): Promise<ContractTransaction>;

  "registerOperator()"(overrides?: Overrides): Promise<ContractTransaction>;

  callStatic: {
    hasOperator(addr: string, overrides?: CallOverrides): Promise<boolean>;

    "hasOperator(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    metaspacecyAccessControls(overrides?: CallOverrides): Promise<string>;

    "metaspacecyAccessControls()"(overrides?: CallOverrides): Promise<string>;

    registerOperator(overrides?: CallOverrides): Promise<void>;

    "registerOperator()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    hasOperator(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    "hasOperator(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    metaspacecyAccessControls(overrides?: CallOverrides): Promise<BigNumber>;

    "metaspacecyAccessControls()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerOperator(overrides?: Overrides): Promise<BigNumber>;

    "registerOperator()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    hasOperator(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hasOperator(address)"(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    metaspacecyAccessControls(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "metaspacecyAccessControls()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerOperator(overrides?: Overrides): Promise<PopulatedTransaction>;

    "registerOperator()"(overrides?: Overrides): Promise<PopulatedTransaction>;
  };
}
